version: 2
formats:
  - htmlzip
  - epub
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    create_environment:
      - python3 -m venv venv
      - venv/bin/python3 -m pip install -c ci/constraints.txt -r ci/requirements.docs.txt
      - venv/bin/python3 -m pip install --config-settings=--build-option=--no-c-backend .
    build:
      htmlzip:
        - make -C docs html SPHINXBUILD=$(pwd)/venv/bin/sphinx-build BUILDDIR=$READTHEDOCS_OUTPUT
      epub:
        - make -C docs epub SPHINXBUILD=$(pwd)/venv/bin/sphinx-build
        - cp docs/_build/epub/python-zstandard.epub  "${READTHEDOCS_OUTPUT}/"
