[project]
name = "zstandard"
dynamic = ["version"]
description = "Zstandard bindings for Python"
readme = { file = "README.rst", content-type = "text/x-rst" }
authors = [
    { name = "Gregory Szorc", email = "gregory.szorc@gmail.com" },
]
license = { text = "BSD" }
requires-python = ">=3.9"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: C",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
keywords = ["zstandard", "zstd", "compression"]
dependencies = []

[project.optional-dependencies]
cffi = [
    'cffi>=2.0.0b1 ; python_version >= "3.13" and platform_python_implementation != "PyPy"',
]

[project.urls]
Homepage = "https://github.com/indygreg/python-zstandard"
Documentation = "https://python-zstandard.readthedocs.io/en/latest/"

[build-system]
requires = [
    "cffi>=2.0.0b1 ; platform_python_implementation != 'PyPy'",
    "packaging",
    "setuptools",
]
# Need to use legacy backend because setup_zstd.py breaks build isolation.
build-backend = "setuptools.build_meta:__legacy__"

[dependency-groups]
dev = [
    "hypothesis==6.111.0",
    "mypy>=1.17.1",
    "pytest>=8.4.1",
    "pytest-xdist>=3.8.0",
]

[tool.ruff]
line-length = 80

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]

[tool.cibuildwheel]
enable = ["cpython-prerelease"]

# This is needed to suppress generation of license-file, which isn't
# compatible with metadata version 2.1, which our pinned setuptools
# version currently uses.
# TODO delete this after we adopt modern setuptools.
[tool.setuptools]
license-files = []

[tool.uv]
build-constraint-dependencies = [
    # 69.0.0 breaks handling of --config-settings=--build-option, which our CI
    # relies on. So constrained to an older version until we figure out a
    # workaround. See comment at
    # https://github.com/pypa/pip/issues/11859#issuecomment-2132287974.
    "setuptools<69.0.0",
]
