on:
  push:
  pull_request:
  schedule:
    - cron: '30 13 * * *'
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: astral-sh/ruff-action@v1
