on:
  push:
  pull_request:
  schedule:
    - cron: '30 13 * * *'
jobs:
  sdist:
    runs-on: 'ubuntu-22.04'
    steps:
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.9'

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Build sdist
        run: |
          python -m pip install -r ci/requirements.txt
          python setup.py sdist

      - name: Upload sdist
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          path: dist
