on:
  push:
  pull_request:
  schedule:
    - cron: '30 13 * * *'
jobs:
  sphinx:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@d9e0f98d3fc6adb07d1e3d37f3043649ddad06a1 # v6.5.0
        with:
          version: "0.8.11"
      - name: Run Sphinx
        env:
          PIP_CONSTRAINT: 'ci/constraints.txt'
        run: |
          uv venv --python 3.12 venv
          source venv/bin/activate
          uv pip install -r ci/requirements.txt
          uv pip install --config-settings=--build-option=--no-c-backend .
          uv pip install Sphinx==5.3.0
          make -C docs html
