on:
  push:
  pull_request:
  schedule:
    - cron: '30 13 * * *'
permissions: { }
jobs:
  sphinx:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@d9e0f98d3fc6adb07d1e3d37f3043649ddad06a1 # v6.5.0
        with:
          version: "0.8.11"
      - name: Run Sphinx
        run: |
          uv venv --python 3.13 venv
          source venv/bin/activate
          uv pip install -r ci/requirements.docs.txt
          uv pip install --config-settings=--global-option=--no-c-backend .
          make -C docs html
