on:
  push:
  pull_request:
  schedule:
    - cron: '30 13 * * *'
jobs:
  mypy:
    strategy:
      fail-fast: false
      matrix:
        py:
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.11"

      - name: Install Dependencies
        run: |
          uv venv --python ${{ matrix.py }} venv
          source venv/bin/activate
          uv pip install -r ci/requirements.txt

      - name: Run mypy
        run: |
          venv/bin/mypy tests/*.py zstandard/*.py
